### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by SetScript** [Largo/ocran#1]
A great fork of the ocra library for new ruby version!

**Comment by ccorn90** [comment]
I agree.  I used `ocra` on a couple of projects back in the day and this has been very helpful with the new Ruby.  Thanks @Largo .

**Comment by imbrish** [comment]
Great to see that! I have previously tried to contribute to ocra, but was unable due to author inactivity. Will be glad to use your fork when the time comes 🥳
