### ISSUE TITLE
Eliminating the --no-lzma option

### ISSUE THREAD

**Issue by shinokaro** [Largo/ocran#15]
I propose making LZMA compression a default feature of stub, which means eliminating the --no-lzma option.
Even when using InnoSetup, the state of the --no-lzma option had no impact on the actual application startup behavior before the fork from OCRA.
I cannot find any practical scenarios where an uncompressed mode in stub is necessary.
Does anyone require the --no-lzma option?

**Comment by Largo** [comment]
The .exe can be built faster with this option, which is nice for testing. Maybe we should keep it.

**Comment by shinokaro** [comment]
I have also observed that using LZMA compression increases test durations. In my environment, it appears to take twice as long compared to uncompressed mode. Although we have significantly reduced the time it takes for LZMA compression in past OCRAN improvements, there is no further prospect of shortening this duration.

We need to retain the --no-lzma option.
