### ISSUE TITLE
Should we support Ruby 2.x?

### ISSUE THREAD

**Issue by shinokaro** [Largo/ocran#17]
Should we support Ruby 2,6?
The version of RubyGems attached to Ruby2,6 is 3.0.3.1 and the following warning is reported when running tests in CI:
```
Your RubyGems version (3.0.3.1) has a bug that prevents `required_ruby_version` from working for Bundler.
Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version.
Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
```

Should we support Ruby 2,7?
Ruby 2.6 and 2.7 will no longer be supported from Bundler 2.5.
https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#breaking-changes
If we support Ruby 2.7, we will not be able to upgrade the version of Bundler.

**Comment by shinokaro** [comment]
My opinion is to drop support for Ruby 2.x.

We want to test against all versions of Ruby that we support.
Ruby changes every year and is unstable as an application execution environment.
And we will be maintaining the Gemfile at the time of Ruby 3.4.
That's why you need our support at all times.

In addition, GEM (minitest, hoe), which is required by OCRAN, will also end support for Ruby 2.x in the near future.

Ruby on Windows has been UTF-8 since 3.0 (https://bugs.ruby-lang.org/issues/13571).
This solves one of the problems with the handling of multibyte strings in OCRAN.

**Comment by shinokaro** [comment]
> We want to test against all versions of Ruby that we support.
@Largo

**Comment by Largo** [comment]
Ok, we can drop old Ruby Versions, but make a note in the changelog, so users will now which version still works?

**Comment by Largo** [comment]
we dropped support for versions below ruby 3 in the new 1.3.16 release.
