### ISSUE TITLE
win7 x86 support   (win32)

### ISSUE THREAD

**Issue by sevk** [Largo/ocran#18]
file:  a.rb   ( oneline )  :
> p RUBY_DESCRIPTION 

C:\Users\Administrator>ocran a.rb
=== Loading script to check dependencies
"ruby 3.2.2 (2023-03-30 revision e51014f9c0) [i386-mingw32]"
...
LZMA 22.01 (x86) : Igor Pavlov : Public domain : 2022-07-15

Input size:  9667016 (9 MiB)
Output size: 2436907 (2 MiB)
=== Finished building a.exe (2485567 bytes)

C:\Users\Administrator>a.exe
This version of C:\Users\Administrator\a.exe is not compatible with the version
of Windows you're running. Check your computer's system information to see wheth
er you need a x86 (32-bit) or x64 (64-bit) version of the program, and then cont
act the software publisher.

C:\Users\Administrator>systeminfo | findstr -i type 
System Type:               X86-based PC

C:\Users\Administrator>ver
Microsoft Windows [Version 6.1.7601]

**Comment by Largo** [comment]
Hi! You can fork the repository and use an older LZMA version. Alternatively you can look into the documentation how to not use lzma.

You can also use an older ruby version with ocra.

We won't support 32bit.
