### ISSUE TITLE
Unable to Release OCRAN 1.3.16

### ISSUE THREAD

**Issue by shinokaro** [Largo/ocran#24]
I am unable to release OCRAN version 1.3.16. Could someone guide me on what steps to take to resolve this issue? Any assistance would be greatly appreciated. Thank you.

**Comment by shinokaro** [comment]
https://github.com/Largo/ocran/releases/tag/1.3.16
I have created the 1.3.16 gem, but I was unable to upload it to RubyGems.org.

**Comment by Largo** [comment]
Thanks a lot! I released it!

**Comment by shinokaro** [comment]
Thank you. Now I can go to sleep.
