### ISSUE TITLE
Compile to 32 bit

### ISSUE THREAD

**Issue by SimoLRepo** [Largo/ocran#29]
Hello, would it be possible to add an option to compile in 32-bit? If scripts are compiled in 64 bit they will not work on 32-bit computers. Thank you.

**Comment by shinokaro** [comment]
Only the 64-bit version will be distributed. The Git repository contains the source code, so you can compile the 32-bit version yourself.

**Comment by SimoLRepo** [comment]
When compiling, several errors are returned that do not appear if compiled in 64-bit (including SIZE_MAX). I `#include <stdint.h>` but other errors appeared. The original ocra project is compiled in 32-bit, I don't understand the reason to distribute only the 64-bit version. Thanks anyway.
