### ISSUE TITLE
Reporting Errors When Using the `--innosetup` Option

### ISSUE THREAD

**Issue by shinokaro** [Largo/ocran#5]
When using the `--innosetup` option, the following error message is reported by ISCC:
```
Error in C:\Users\(my project folder)\ocrantemp.iss: the process cannot access the file because it is being used by another process.
```

https://github.com/Largo/ocran/blob/0ace7ed8044e895d93f7c16308c03d04e9252e2c/bin/ocran#L1184

Here, the IO to the `ocrantemp.iss` file is being closed, but it seems that Ruby has not released the file yet.
※ After adding `GC.start` right after this line of code, ISCC continued to execute.

If execution is continued, the following error is reported by ISCC:
```
Error on line 509 in C:\Users\(my project folder)\ocrantemp.iss: Source file "C:/Users/(user name)/AppData/Local/Temp/msys-2.0.dll20231003-14956-sga45n" does not exist.
```

**Comment by Largo** [comment]
Hello!

I'm currently on a bus to Fukuoka, so I cannot do much.

Can I have your ruby version and windows version?

Also please try putting the projectfolder outside of c:/user.

Maybe c:\workspace\projectfolder

And also try a minimal example like

helloworld.rb: 
  puts 'hello world'

ocran helloworld.rb --innosetup

**Comment by shinokaro** [comment]
development environment:
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x64-mingw-ucrt]
Windows11 22H2(build 22621.2283)

I tried a minimal example, but the same error occurred.

**Comment by shinokaro** [comment]
I have created a pull request to address the first issue.

The second issue is related to the usage of `Tempfile` in a Windows environment. (Files created with `NamedTemporaryFile` cannot be accessed from another process). There are comments in the code explaining this issue, so I am considering making modifications, including addressing the comments.

**Comment by shinokaro** [comment]
The current workaround to ensure consistent behavior is to close `ocrantemp.iss` and then call `GC.start`. However, the root cause remains unclear, and this is not a technical resolution.

**Comment by shinokaro** [comment]
https://github.com/Largo/ocran/commit/52de3bbbae673cb825e8cfb1dfec9708f0c7478e
https://github.com/Largo/ocran/commit/b431ecaf29bd4181c42ee1d55ead6b0065a18a0d

この文を英語に翻訳すると次のようになります：

"This issue has been resolved with two commits."
